apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-cd

bases:
  - github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.1.1

resources:
  - resources/namespace.yaml